### PR TITLE
PS-3117 Update OM

### PR DESCRIPTION
**Pull request by joker806**
https://keboola.atlassian.net/browse/PS-3117

### CODE REVIEW

**Review by pivnicek — APPROVED** [review]
Dik!

**Comment by joker806** [comment]
@pivnicek will you do merge etc.?

**Comment by pivnicek** [comment]
@joker806 what is "etc"? 😄 .  is there some other step for releasing?

**Comment by joker806** [comment]
:man_shrugging: I don't know. What I meant by the "etc." is that I can put my hands off, not thinking of any following steps, if required :smile:

**Pull request merged**
